### ISSUE TITLE
Add tag for github release

### ISSUE THREAD

**Issue by cades** [schreifels/git-num#1]
Hi @schreifels,

thanks for your work, this is cool!

I want to submit a formula to homebrew, but found it requires version number in download url.

currently we can access tarball via `https://github.com/schreifels/git-num/archive/master.tar.gz`.
and if we have a release, we can access tarball via `https://github.com/schreifels/git-num/releases/download/1.0/git-num-1.0.tar.gz`

 Could you add tag (and github release)?

**Comment by schreifels** [comment]
Absolutely, @cades , thanks for your interest! You can now get the (versioned) executable here:

https://github.com/schreifels/git-num/releases/download/v1.0.0/git-num

or the full source here:

https://github.com/schreifels/git-num/archive/v1.0.0.tar.gz

Feel free to ping me when you're done -- I'd be happy to update the `README` to reference installation through homebrew.
