### ISSUE TITLE
No numbers

### ISSUE THREAD

**Issue by tino** [schreifels/git-num#7]
I don't see any numbers. The output is identical to `git status`. See here:
![CleanShot 2024-01-22 at 14 19 18](https://github.com/schreifels/git-num/assets/99524/2cc77c63-7aa8-4a16-9eb2-9b12882364fd)

```shell
❯ git num -v
git-num version 4.0.1
```

I'm on macOS 14.1, on zsh.

**Comment by schreifels** [comment]
Hi @tino - To help debug, could you please:
* Let me know what `git -v` outputs
* In a Git repo with changed files (like in your screenshot), run `git -c color.status=always -c status.short=false status > git-status-output.txt` and upload git-status-output.txt here (so that I can see the raw Git output, including the escape sequences for the colors)

Cheers!

**Comment by tino** [comment]
```sh
❯ git -v
git version 2.42.1
```

[git-status-output.txt](https://github.com/schreifels/git-num/files/14024420/git-status-output.txt)

Note:
```sh
❯ which git
git: aliased to /opt/homebrew/bin/hub
```

**Comment by schreifels** [comment]
Thanks for sharing that output, @tino! I wasn't able to repro using zsh + Git 2.42.x, but the file you provided gave me what I needed to fix the issue (presumably it's something specific to your `.gitconfig`). This is addressed in 8da37b690a31906909e70686e20dba74a0ead5ad.

Could you please confirm that it's working as expected now? You can either compile from source, or here is the binary:
* [git-num-macos-amd64.tar.gz](https://github.com/schreifels/git-num/files/14074422/git-num-macos-amd64.tar.gz)
* [git-num-macos-arm64.tar.gz](https://github.com/schreifels/git-num/files/14074423/git-num-macos-arm64.tar.gz)

If everything looks good, I can cut a release that includes the fix.

**Comment by schreifels** [comment]
I released this as v4.0.2. Feel free to re-open this issue if you try it out and have any more issues. Thanks for the report!

**Comment by tino** [comment]
@schreifels apologies for not coming back. I tested it and it works indeed!

**Comment by schreifels** [comment]
No worries, great to hear, thanks Tino!
